package eu.kakde.sonatypecentral

import com.google.gson.GsonBuilder
import eu.kakde.sonatypecentral.api.BundleLayout
import eu.kakde.sonatypecentral.api.Credentials
import eu.kakde.sonatypecentral.api.OkHttpSonatypeCentralClient
import eu.kakde.sonatypecentral.api.PublishingType
import eu.kakde.sonatypecentral.api.SonatypeCentralClient
import eu.kakde.sonatypecentral.utils.HashUtils
import eu.kakde.sonatypecentral.utils.MessageDigestAlgorithm
import eu.kakde.sonatypecentral.utils.ZipUtils
import org.gradle.api.DefaultTask
import org.gradle.api.publish.maven.MavenPublication
import org.gradle.api.publish.maven.internal.publication.MavenPublicationInternal
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.TaskAction
import org.gradle.plugins.signing.SigningExtension
import java.io.File
import java.nio.file.Files
import java.nio.file.attribute.PosixFilePermissions
import java.security.MessageDigest
import java.util.Locale
import javax.inject.Inject

abstract class SignMavenArtifact
    @Inject
    constructor(
        @Internal val mavenPublication: MavenPublication,
    ) : DefaultTask() {
        init {
            this.dependsOn("generateMavenArtifacts")

            group = CUSTOM_TASK_GROUP
            description = "Sign necessary artifacts generated by 'generateMavenArtifacts'."
        }

        private val signingExtension: SigningExtension = project.extensions.getByType(SigningExtension::class.java)

        @TaskAction
        fun action() {
            println("Executing 'signMavenArtifact' Task...")
            val internalPublication = mavenPublication as MavenPublicationInternal
            internalPublication.publishableArtifacts.forEach {
                signingExtension.sign(it.file)
            }
        }
    }

abstract class AggregateFiles
    @Inject
    constructor(
        @Internal val layout: BundleLayout,
    ) : DefaultTask() {
        init {
            this.dependsOn("signMavenArtifacts")

            group = CUSTOM_TASK_GROUP
            description = "Aggregate all files to a temporary directory."
        }

        @TaskAction
        fun action() {
            println("Executing AggregateFiles")

            val artifactId = layout.coordinates.artifactId
            val version = layout.coordinates.version
            val filesToAggregate = mutableListOf<File>()
            val buildDirectory = project.layout.buildDirectory

            // Add all files from the libs directory
            val libsDir = buildDirectory.dir("libs").get().asFileTree
            // Todo: improve this code. Remove generation of plain jar file in publication.
            val filesToAdd =
                libsDir.files.filter { file ->
                    !file.name.endsWith("-plain.jar") && !file.name.endsWith("-plain.jar.asc")
                }
            filesToAggregate.addAll(filesToAdd)

            // Rename and Add all files from the publications/maven directory, e.g. pom-default.xml and pom-default.xml.asc
            val mavenPublicationsDir = buildDirectory.dir("publications/maven").orNull
            mavenPublicationsDir?.asFileTree?.forEach { file: File ->
                val newName =
                    when {
                        file.name == "pom-default.xml" -> "$artifactId-$version.pom"
                        file.name == "pom-default.xml.asc" -> "$artifactId-$version.pom.asc"
                        file.name == "module.json" -> "$artifactId-$version.module"
                        file.name == "module.json.asc" -> "$artifactId-$version.module.asc"
                        else -> "$artifactId-$version.${file.name}"
                    }
                filesToAggregate.add(renameFile(file, newName))
            }

            val versionCatalogDir = buildDirectory.dir("version-catalog").orNull
            versionCatalogDir?.asFileTree?.forEach { file ->

                val fileName = file.name
                val newName =
                    when {
                        fileName.endsWith("versions.toml") -> "$artifactId-$version.toml"
                        fileName.endsWith("versions.toml.asc") -> "$artifactId-$version.toml.asc"
                        else -> fileName
                    }

                filesToAggregate.add(renameFile(file, newName))
            }

            val tempDirFile = createStagingDirectory(layout.stagingDirectory)
            filesToAggregate.forEach { file ->
                file.copyTo(tempDirFile.resolve(file.name), overwrite = true)
            }
        }

        private fun createStagingDirectory(directory: File): File {
            directory.mkdirs()
            // Windows file systems do not expose the POSIX attribute view; skip there. (#4)
            if (directory.toPath().fileSystem.supportedFileAttributeViews().contains("posix")) {
                Files.setPosixFilePermissions(
                    directory.toPath(),
                    PosixFilePermissions.fromString("rwxrwxrwx"),
                )
            }
            return directory
        }

        private fun renameFile(
            oldFile: File,
            newFileName: String,
        ): File {
            require(oldFile.exists()) { "File does not exist: ${oldFile.absolutePath}" }
            val parentDir = checkNotNull(oldFile.parentFile) { "Parent directory is null" }
            val newFile = File(parentDir, newFileName)
            check(oldFile.renameTo(newFile)) { "Failed to rename file: ${oldFile.absolutePath}" }
            return newFile
        }
    }

abstract class ComputeHash
    @Inject
    constructor(
        @Internal val layout: BundleLayout,
        @Internal val shaAlgorithms: List<String>,
    ) : DefaultTask() {
        init {
            group = CUSTOM_TASK_GROUP
            description = "Compute Hash of all files in a temporary directory."
            this.dependsOn("aggregateFiles")
        }

        @TaskAction
        fun run() {
            println("Executing 'computeHash' Task...")
            // Maven Central requires MD5 + SHA-1 alongside any user-requested
            // algorithms. Deduplicate so a user who already lists SHA-1 doesn't
            // produce two .sha1 files.
            val effectiveAlgorithms =
                (listOf(MessageDigestAlgorithm.MD5, MessageDigestAlgorithm.SHA_1) + shaAlgorithms).toSet()
            println("Hash algorithms used: $effectiveAlgorithms")
            val directory = layout.stagingDirectory
            directory.listFiles { _, name -> !name.endsWith(".asc") }?.forEach { file ->
                effectiveAlgorithms.forEach { algorithm ->
                    val digest = MessageDigest.getInstance(algorithm)
                    val checksum = HashUtils.getCheckSumFromFile(digest, file)
                    val checksumFile = File(directory, "${file.name}.${fileSuffixFor(algorithm)}")
                    checksumFile.writeText(checksum)
                }
            }
        }

        private fun fileSuffixFor(algorithm: String): String =
            algorithm.replace("-", "").lowercase(Locale.ROOT)
    }

abstract class CreateZip
    @Inject
    constructor(
        @Internal val layout: BundleLayout,
    ) : DefaultTask() {
        init {
            group = CUSTOM_TASK_GROUP
            description = "Create a zip file comprising all files located within a temporary directory."
            this.dependsOn("computeHash")
        }

        @TaskAction
        fun createArchive() {
            println("Executing 'createZip' task...")
            println("Creating zip file from the folder: ${layout.uploadRootDirectory.path}")
            ZipUtils.prepareZipFile(layout.uploadRootDirectory.path, layout.zipFile.path)
        }
    }

abstract class PublishToSonatypeCentral
    @Inject
    constructor(
        @Internal val layout: BundleLayout,
    ) : DefaultTask() {
        init {
            group = CUSTOM_TASK_GROUP
            description = "Publish to New Sonatype Maven Central Repository."
            this.dependsOn("createZip")
        }

        private val extension = project.extensions.getByType(SonatypeCentralPublishExtension::class.java)

        @Internal
        var client: SonatypeCentralClient? = null

        @TaskAction
        fun uploadZip() {
            logger.lifecycle("Executing 'publishToSonatypeCentral' task...")
            val effectiveClient = client ?: defaultClient(extension)
            val publishingType = PublishingType.valueOf(extension.publishingType.get().uppercase(Locale.ROOT))

            val deploymentId = effectiveClient.upload(layout.zipFile, layout.coordinates, publishingType)
            logger.lifecycle("Published to Maven Central. Deployment ID: ${deploymentId.value}")
        }
    }

abstract class GetDeploymentStatus : DefaultTask() {
    init {
        group = CUSTOM_TASK_GROUP
        description = "Get deployment status using deploymentId"
    }

    @Input
    var deploymentId: String = project.findProperty("deploymentId")?.toString() ?: ""

    private val extension = project.extensions.getByType(SonatypeCentralPublishExtension::class.java)

    @Internal
    var client: SonatypeCentralClient? = null

    @TaskAction
    fun executeTask() {
        logger.lifecycle("Executing 'getDeploymentStatus' task... With parameter deploymentId=$deploymentId")
        val effectiveClient = client ?: defaultClient(extension)
        val status = effectiveClient.status(deploymentId)
        val pretty = GsonBuilder().setPrettyPrinting().create().toJson(status)
        logger.lifecycle("Deployment Status:\n$pretty")
    }
}

abstract class DropDeployment : DefaultTask() {
    init {
        group = CUSTOM_TASK_GROUP
        description = "Drop deployment using deploymentId."
    }

    @Input
    var deploymentId: String = project.findProperty("deploymentId")?.toString() ?: ""

    private val extension = project.extensions.getByType(SonatypeCentralPublishExtension::class.java)

    @Internal
    var client: SonatypeCentralClient? = null

    @TaskAction
    fun executeTask() {
        logger.lifecycle("Executing 'dropDeployment' task... Dropping deployment for deploymentId=$deploymentId")
        val effectiveClient = client ?: defaultClient(extension)
        effectiveClient.drop(deploymentId)
        logger.lifecycle("Deployment Dropped Successfully for Deployment ID: $deploymentId")
    }
}

private fun defaultClient(extension: SonatypeCentralPublishExtension): SonatypeCentralClient {
    val credentials = Credentials(extension.username.get(), extension.password.get())
    return OkHttpSonatypeCentralClient(credentials)
}
