/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package eu.kakde.sonatypecentral

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'eu.kakde.gradle.sonatype-maven-central-publish' plugin.
 */
class SonatypeMavenCentralPublisherPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("eu.kakde.gradle.sonatype-maven-central-publish")

        // Verify the result
        assertNotNull(project.tasks.findByName("signedMavenArtifactTask"))
    }
}
